Patch files
schottkey7/digit-span-mnemonics pull request #21
Opened 2018-08-28 15:27 UTC by schottkey7

2018-09-04 12:12 UTC, schottkey7 commented on src/testModify.js
> +const testUser = "admin";
another comment

2018-09-04 12:16 UTC, schottkey7 commented on src/index.js
> -        jsState[mode][variable] = immutable[type](jsState[mode][variable]);
comment between lines 21 and 22.

2018-09-04 13:01 UTC, schottkey7 commented on tests/actions.tests.js
> -test("generate action to change mode (navigation)", t => {
Test line 8

2018-09-04 13:03 UTC, schottkey7 commented on src/utils.js
> -export const numToLetter = fromJS({
4th line of first block

2018-09-04 13:03 UTC, schottkey7 commented on src/utils.js
> -export function getEmoji(p: number) {
4th line of second block

2018-09-05 11:30 UTC, schottkey7 commented on src/containers/Games.js
> -  actions: bindActionCreators(actions, dispatch),
Some random comment (part of a review)

2018-09-05 11:31 UTC, schottkey7 commented on src/index.js
>  import {initialState, typeConversions} from "./constants";
lala (just a single comment, not part of review)

2018-09-05 12:04 UTC, nora-petrova requested changes
Needs changes

2018-09-06 10:43 UTC, schottkey7 commented
Test update

2018-09-06 11:18 UTC, schottkey7 commented
Comment

2018-09-06 11:23 UTC, nlpet commented
More comments

2018-09-06 14:49 UTC, schottkey7 commented
Mooore

2018-09-10 12:25 UTC, closed without merging